
# Week 2 — Day 2: Advanced Pandas Operations

## Learning Objectives
- Merge multiple DataFrames using different join types.
- Summarise data using pivot tables.
- Reshape data using `pd.melt()`.
- Combine operations using method chaining.

## Dataset
We will use sample sales and product datasets to practise advanced Pandas operations.

In [1]:

import pandas as pd

# Sales dataset
sales = pd.DataFrame({
    "OrderID": [101, 102, 103, 104, 105],
    "Region": ["North", "South", "East", "West", "North"],
    "ProductID": [1, 2, 1, 3, 2],
    "Sales": [1200, 900, 1500, 700, 1100]
})

# Product dataset
products = pd.DataFrame({
    "ProductID": [1, 2, 3, 4],
    "Product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "Category": ["Electronics", "Electronics", "Electronics", "Accessories"]
})

print("SALES DATA")
display(sales)

print("PRODUCT DATA")
display(products)

SALES DATA

   OrderID Region  ProductID  Sales
0      101  North          1   1200
1      102  South          2    900
2      103   East          1   1500
3      104   West          3    700
4      105  North          2   1100

PRODUCT DATA

   ProductID  Product     Category
0          1   Laptop  Electronics
1          2    Phone  Electronics
2          3   Tablet  Electronics
3          4  Monitor  Accessories

In [2]:

# 1. INNER JOIN: only matching ProductIDs
inner_join = pd.merge(sales, products, on="ProductID", how="inner")
print("INNER JOIN")
display(inner_join)

# 2. LEFT JOIN: all sales rows, matching product details
left_join = pd.merge(sales, products, on="ProductID", how="left")
print("LEFT JOIN")
display(left_join)

# 3. RIGHT JOIN: all products, matching sales records
right_join = pd.merge(sales, products, on="ProductID", how="right")
print("RIGHT JOIN")
display(right_join)

# 4. OUTER JOIN: all sales and all products
outer_join = pd.merge(sales, products, on="ProductID", how="outer")
print("OUTER JOIN")
display(outer_join)

INNER JOIN

   OrderID Region  ProductID  Sales Product     Category
0      101  North          1   1200  Laptop  Electronics
1      102  South          2    900   Phone  Electronics
2      103   East          1   1500  Laptop  Electronics
3      104   West          3    700  Tablet  Electronics
4      105  North          2   1100   Phone  Electronics

LEFT JOIN

   OrderID Region  ProductID  Sales Product     Category
0      101  North          1   1200  Laptop  Electronics
1      102  South          2    900   Phone  Electronics
2      103   East          1   1500  Laptop  Electronics
3      104   West          3    700  Tablet  Electronics
4      105  North          2   1100   Phone  Electronics

RIGHT JOIN

   OrderID Region  ProductID   Sales  Product     Category
0    101.0  North          1  1200.0   Laptop  Electronics
1    103.0   East          1  1500.0   Laptop  Electronics
2    102.0  South          2   900.0    Phone  Electronics
3    105.0  North          2  1100.0    Phone  Electronics
4    104.0   West          3   700.0   Tablet  Electronics
5      NaN    NaN          4     NaN  Monitor  Accessories

OUTER JOIN

   OrderID Region  ProductID   Sales  Product     Category
0    101.0  North          1  1200.0   Laptop  Electronics
1    103.0   East          1  1500.0   Laptop  Electronics
2    102.0  South          2   900.0    Phone  Electronics
3    105.0  North          2  1100.0    Phone  Electronics
4    104.0   West          3   700.0   Tablet  Electronics
5      NaN    NaN          4     NaN  Monitor  Accessories

In [3]:

# Create a pivot table: total sales by region and product
pivot_sales = pd.pivot_table(
    sales.merge(products, on="ProductID", how="left"),
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)

print("TOTAL SALES BY REGION AND PRODUCT")
display(pivot_sales)

TOTAL SALES BY REGION AND PRODUCT

Product  Laptop  Phone  Tablet
Region
East       1500      0       0
North      1200   1100       0
South         0    900       0
West          0      0     700

In [4]:

# Create a wide-format dataset
monthly_sales = pd.DataFrame({
    "Product": ["Laptop", "Phone", "Tablet"],
    "January": [1200, 900, 700],
    "February": [1500, 1100, 850],
    "March": [1800, 1300, 950]
})

print("WIDE FORMAT")
display(monthly_sales)

# Convert wide format to long format
long_sales = pd.melt(
    monthly_sales,
    id_vars=["Product"],
    var_name="Month",
    value_name="Sales"
)

print("LONG FORMAT")
display(long_sales)

WIDE FORMAT

  Product  January  February  March
0  Laptop     1200      1500   1800
1   Phone      900      1100   1300
2  Tablet      700       850    950

LONG FORMAT

  Product     Month  Sales
0  Laptop   January   1200
1   Phone   January    900
2  Tablet   January    700
3  Laptop  February   1500
4   Phone  February   1100
5  Tablet  February    850
6  Laptop     March   1800
7   Phone     March   1300
8  Tablet     March    950

In [5]:

# Filter, sort, and select columns in one pipeline
result = (
    sales
    .query("Sales >= 1000")
    .sort_values("Sales", ascending=False)
    .loc[:, ["OrderID", "Region", "Sales"]]
    .reset_index(drop=True)
)

print("FILTERED AND SORTED SALES")
display(result)

FILTERED AND SORTED SALES

   OrderID Region  Sales
0      103   East   1500
1      101  North   1200
2      105  North   1100


## Merge vs Concatenate

### `pd.merge()`
- Combines DataFrames using one or more common columns or keys.
- Supports inner, left, right, and outer joins.
- Example: Combining sales records with product details using `ProductID`.

### `pd.concat()`
- Combines DataFrames along rows or columns.
- Does not require a shared key column.
- Example: Appending January sales records to February sales records.

### Key Difference
`merge()` matches related records using keys, whereas `concat()` stacks or places DataFrames alongside each other.


## Conclusion

In this practical, I used Pandas to combine multiple DataFrames, summarise sales by region and product, reshape data from wide to long format, and chain multiple operations into a readable pipeline. These techniques help prepare and analyse structured datasets efficiently.